# Generated by Django 5.1.3 on 2025-01-20 06:27

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillNumberTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(blank=True, max_length=4, null=True, validators=[api.models.validate_prefix])),
            ],
        ),
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_number', models.IntegerField()),
                ('book_number', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('client_address', models.TextField()),
                ('client_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'In-Active')], max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_company_owner', models.BooleanField(default=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_number', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='create_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('amount_receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.clientmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='advance_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('upi', 'UPI')], max_length=50, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_list_company', to='api.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance', to='api.create_bill')),
            ],
        ),
        migrations.CreateModel(
            name='LowerMaap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_maap', models.CharField(blank=True, choices=[('pathani_salwar', 'Pathani Salwaar'), ('aligari', 'Aligari'), ('payjama', 'Payjama'), ('chudidar', 'Chudidaar'), ('pant', 'Pant'), ('others', 'Others')], max_length=50, null=True)),
                ('lower_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_hip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_thai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_knee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_bottom', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_jhola', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_other_remark', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower_maaps', to='api.clientmaster')),
            ],
        ),
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list_company', to='api.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.create_bill')),
                ('product_assignedTo', models.ForeignKey(blank=True, limit_choices_to={'employee_status': 'active', 'is_company_owner': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpperMaap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_maap', models.CharField(blank=True, choices=[('zubba', 'Zubba'), ('kurta', 'Kurta'), ('shirt', 'Shirt'), ('blazer', 'Blazer'), ('koty', 'Koty'), ('others', 'Others')], max_length=50, null=True)),
                ('upper_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_sleeve_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_sleeve_bicep', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_sleeve_cuff', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_chest_body', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_chest_ready', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_lowerchest_body', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_lowerchest_ready', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_stomach_body', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_stomach_ready', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_hip_body', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_hip_ready', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_neck', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('upper_other_remark', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_maaps', to='api.clientmaster')),
            ],
        ),
    ]
