# Generated by Django 5.0.6 on 2026-01-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowermaap',
            name='lower_design_image',
            field=models.ImageField(blank=True, null=True, upload_to='maap/lower/design/'),
        ),
        migrations.AddField(
            model_name='uppermaap',
            name='upper_design_image',
            field=models.ImageField(blank=True, null=True, upload_to='maap/upper/design/'),
        ),
    ]
