# Generated by Django 5.0.6 on 2026-02-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lowermaap_lower_design_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmaster',
            name='client_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
