# Generated by Django 5.0.6 on 2026-02-02 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_lowermaap_lower_design_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_step', models.CharField(choices=[('clients', 'Clients'), ('maap', 'Maap'), ('bills', 'Bills'), ('products', 'Products'), ('done', 'Done')], default='clients', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
